### ISSUE TITLE
About the input resolution

### ISSUE THREAD

**Issue by xiaoiker** [pputzky/irim_fastMRI#2]
Hello, thanks for releasing the source code. Can I ask a question?

I found from the script that the image you used to train the network is with the size of 368*368 (--train_resolution 368 368), I really want to ask why since the references are with size 320*320. Did you also try to train with 320*320? If so, how about the result? 

Thanks a lot.

**Comment by pputzky** [comment]
Great question! 

First, let me start with this: During test time we will have to perform reconstructions on the whole volume without cropping in order to have a correct forward model. Only after reconstruction will we be able to do cropping. Now ideally, we want our measurement simulations during training to resemble those during test time as closely as possible. However, due to the fact that all volumes have vastly different sizes and some of them are very large, working on full volumes during training would be computationally restrictive.

Therefore, we train on smaller patches. We know that by doing this, training and test data will not come from the same distribution. Empirically, however, we've had good results already with the baseline Recurrent Inference Machine (RIM) by training on smaller patches and transferring to larger patches. But, we have evidence that training on larger patches benefits performance nevertheless (see Lønning et al., 2019).

So the chosen patch size is a trade-off between computational overhead and performance. In the model we trained, the largest receptive field size of a residual block is 24. Now if you add that to the all edges we have 320 + 48 = 368. Working with this slightly larger context than the target is aimed to reduce edge effects.

We have not tried training on 320x320.

Hope this helps!



Lønning, K., Putzky, P., Sonke, J. J., Reneman, L., Caan, M. W., & Welling, M. (2019). Recurrent inference machines for reconstructing heterogeneous MRI data. Medical image analysis, 53, 64-78.
